#----------------
# - kommentarii
#----------------
name: myGitActionsBasics
env:
  APPLICATION_NAME : "QueueSupporter"
  PACKAGE_NAME     : "flame-testing-ver-${{github.sha}}"

on: [push]

jobs:
  my_build:

    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message 
        run: echo "Hello Fara from building"
      - name: Execute few commands
        run: |
          echo "Hello Roo"
          echo "Hello Barsic"
          echo "Application name : ${{env.APPLICATION_NAME}}"
      - name: List current directory
        run: ls -la
      - name: Clone our repository
        uses: actions/checkout@v1
      - name: List current directory
        run: ls -la
      - name: Create directory bin
        run: mkdir bin
      - name: List current directory
        run: ls -la
      - name: Run javac
        run: javac -sourcepath ./src/main/java/ -d bin src/main/java/Main.java
      - name: Run java
        run: java -classpath ./bin Main
    
  my_installing:  
    runs-on: [ubuntu-latest]
    
    needs: [my_build] # - для запуска этой jobы - нужно полное выполнение первой jobы ( добавляет последовательность )

    steps:
      - name: Java version
        run: java -version
      - name: Print Hello Message
        run: echo "Hello Saba from testing"
      - name: Install maven
        run: sudo apt-get -y install maven
      - name: mvn -version
        run: mvn -version
      - name: Execute few commands
        run: |
          echo "Hello Roo"
          echo "Hello Barsic"
          echo "PACKAGE  name : ${{env.PACKAGE_NAME}}"
        
